require 'minitest/autorun'

require_relative 'protein'
require_relative 'dna' # For Protein#rna_count

class TestProtein < Minitest::Test
  def test_motifs
    protein = Protein.new(<<-EOF)
MKNKFKTQEELVNHLKTVGFVFANSEIYNGLANAWDYGPLGVLLKNNLKNLWWKEFVTKQ
KDVVGLDSAIILNPLVWKASGHLDNFSDPLIDCKNCKARYRADKLIESFDENIHIAENSS
NEEFAKVLNDYEISCPTCKQFNWTEIRHFNLMFKTYQGVIEDAKNVVYLRPETAQGIFVN
FKNVQRSMRLHLPFGIAQIGKSFRNEITPGNFIFRTREFEQMEIEFFLKEESAYDIFDKY
LNQIENWLVSACGLSLNNLRKHEHPKEELSHYSKKTIDFEYNFLHGFSELYGIAYRTNYD
LSVHMNLSKKDLTYFDEQTKEKYVPHVIEPSVGVERLLYAILTEATFIEKLENDDERILM
DLKYDLAPYKIAVMPLVNKLKDKAEEIYGKILDLNISATFDNSGSIGKRYRRQDAIGTIY
CLTIDFDSLDDQQDPSFTIRERNSMAQKRIKLSELPLYLNQKAHEDFQRQCQK
    EOF

    assert_equal [ 85, 118, 142, 306, 395 ], protein.motifs('N{P}[ST]{P}')
  end

  def test_rna_count
    protein = Protein.new('MA')
    assert_equal 12, protein.rna_count
  end

  def test_monoisotopic_mass
    protein = Protein.new('SKADYEK')
    assert_in_delta 821.392, protein.monoisotopic_mass, 0.001
  end
end
